# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_valid_api_keys": "10_main.ipynb",
         "api_key_check": "10_main.ipynb",
         "create_app": "10_main.ipynb"}

modules = ["core.py",
           "main.py"]

doc_url = "https://butterp.github.io/html_editable_table/"

git_url = "https://github.com/butterp/html_editable_table/tree/main/"

def custom_doc_links(name): return None
